version: '3'
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: password
  phpfpm:
    extra_hosts:
      - "wp-plugin-primarycategory.local:172.18.0.1"